package fes.aragon.controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import fes.aragon.modelo.Articulo;
import fes.aragon.modelo.Articulos;
import fes.aragon.modelo.Pedido;
import fes.aragon.modelo.Pedidos;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class AdministradorPedidosController extends BaseController implements Initializable {
	@FXML
	private Button btnNuevoPedido;
	@FXML
	private Button btnEditar;
	@FXML
	private Button btnEliminar;
	@FXML
	private Button btnSalir;
	@FXML
	private TableView<Pedido> tablaPedidos;
	@FXML
	private TableColumn<Pedido, Integer> clmId;
	@FXML
	private TableColumn<Pedido, String> clmDireccion;
	@FXML
	private TableColumn<Pedido, String> clmFecha;
	@FXML
	private TableColumn<Pedido, String> clmEstado;
	@FXML
	private TableColumn<Pedido, Double> clmTotal;
	@FXML
	private TableColumn<Pedido, String> clmCliente;

	// Event Listener on Button[#btnNuevoPedido].onAction
	@FXML
	public void nuevoPedido(ActionEvent event) {
	this.nuevaVentana("NuevoPedido");
	}

	// Event Listener on Button[#btnEditar].onAction
	@FXML
	public void editarPedido(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnEliminar].onAction
	@FXML
	public void eliminarPedido(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnSalir].onAction
	@FXML
	public void salirPedido(ActionEvent event) {
		ObservableList<Pedido> grupo = Pedidos.getInstancia().getGrupoPedidos();
		grupo.clear();
		this.cerrarVentana(btnSalir);
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		try {
			this.recogerDatosPedidos();
			ObservableList<Pedido> grupo = Pedidos.getInstancia().getGrupoPedidos();
			for (Pedido pedido : grupo) {
				System.out.println(pedido);
			}
			this.clmId.setCellValueFactory(new PropertyValueFactory<>("id"));
			this.clmDireccion.setCellValueFactory(new PropertyValueFactory<>("direccion"));
			this.clmFecha.setCellValueFactory(new PropertyValueFactory<>("fecha"));
			this.clmEstado.setCellValueFactory(new PropertyValueFactory<>("estado"));
			this.clmTotal.setCellValueFactory(new PropertyValueFactory<>("total"));
			this.clmCliente.setCellValueFactory(new PropertyValueFactory<>("cliente"));
			this.tablaPedidos.setItems(Pedidos.getInstancia().getGrupoPedidos());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}
}
