package fes.aragon.controlador;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AdministradorAceptarController extends BaseController {
	@FXML
	private Button btnClientes;
	@FXML
	private Button btnPedidos;
	@FXML
	private Button btnArticulos;
	@FXML
	private Button btnExtras;

	// Event Listener on Button[#btnClientes].onAction
	@FXML
	public void datosClientes(ActionEvent event) {
		this.nuevaVentana("AdministradorCliente");
	}

	// Event Listener on Button[#btnPedidos].onAction
	@FXML
	public void datosPedidos(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnArticulos].onAction
	@FXML
	public void datosArticulos(ActionEvent event) {
		this.nuevaVentana("AdministradorArticulos");	}

	@FXML
	void datosExtras(ActionEvent event) {
		this.nuevaVentana("AdministradorExtra");
	}
}
