package fes.aragon.controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import fes.aragon.modelo.Articulo;
import fes.aragon.modelo.Articulos;
import fes.aragon.modelo.Cliente;
import fes.aragon.modelo.ClientesPedidos;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class AdministradorArticulosController extends BaseController implements Initializable{
	@FXML
	private Button btnNuevoArticulo;
	@FXML
	private Button btnEditar;
	@FXML
	private Button btnEliminar;
	@FXML
	private Button btnSalir;
	@FXML
	private TableView tablaArticulos;
	@FXML
	private TableColumn<Articulo, String>  clmNombre;
	@FXML
	private TableColumn<Articulo, String>  clmDescripcion;
	@FXML
	private TableColumn<Articulo, Double>  clmPrecio;
	@FXML
	private TableColumn<Articulo, String>  clmLeche;
	@FXML
	private TableColumn<Articulo, String>  clmExtra;
	@FXML
	private TableColumn<Articulo, Boolean>  clmCrema;

	// Event Listener on Button[#btnNuevoArticulo].onAction
	@FXML
	public void nuevoArticulo(ActionEvent event) {
		this.nuevaVentana("NuevoArticulo");
	}
	// Event Listener on Button[#btnEditar].onAction
	@FXML
	public void editarPedido(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEliminar].onAction
	@FXML
	public void eliminarArticulo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalir].onAction
	@FXML
	public void salirArticulo(ActionEvent event) {
		ObservableList<Articulo> grupo=Articulos.getInstancia().getGrupoArticulos();
		grupo.clear();
		this.cerrarVentana(btnSalir);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
			
		try {
			this.recogerDatosArticulos();
			ObservableList<Articulo> grupo=Articulos.getInstancia().getGrupoArticulos();
			for (Articulo art : grupo) {
				System.out.println(art);	
			}
			this.clmNombre.setCellValueFactory(new PropertyValueFactory<>("nombre"));
			this.clmDescripcion.setCellValueFactory(new PropertyValueFactory<>("descripcion"));
			this.clmPrecio.setCellValueFactory(new PropertyValueFactory<>("precio"));
			this.clmLeche.setCellValueFactory(new PropertyValueFactory<>("leche"));
			this.clmExtra.setCellValueFactory(new PropertyValueFactory<>("extra"));
			this.clmCrema.setCellValueFactory(new PropertyValueFactory<>("crema"));
			this.tablaArticulos.setItems(Articulos.getInstancia().getGrupoArticulos());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
