package fes.aragon.controlador;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class ClienteController {
	@FXML
	private TextField txtContraseña;
	@FXML
	private TextField txtCorreo;
	@FXML
	private Button btnCrearCuenta;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnSalir;

	// Event Listener on Button[#btnCrearCuenta].onAction
	@FXML
	public void nuevoCliente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptarCliente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalir].onAction
	@FXML
	public void salirCliente(ActionEvent event) {
		// TODO Autogenerated
	}
}
